### PR TITLE
Map/aggregator

### PR DESCRIPTION
**Pull request by nathanqueija**
https://www.pivotaltracker.com/story/show/156807606
image
image
## Before
image

### CODE REVIEW

**Comment by gusaiani** [comment]
@nathanqueija This is looking really great.

The only detail, in my view very important is: if we're showing "aggregates", we should only show aggregates. And pay the price of showing some "1" aggregates.

This way it will be consistent, and will avoid the cognitive dissonance of seeing two kinds of markers with two different meanings.

Do you agree with the point here?

**Comment by nathanqueija** [comment]
@gusaiani, I understand. The confusion that can generate two types of markers on the map must certainly be taken into account.
My concern is that if we just show the aggregators we will lose the price display initially and in the first zoom levels. I believe that this price display on the map is very attractive for those who are looking for a property. If we only display aggregators, the user will only be able to effectively see prices if they zoom in at least 4 levels.
What do you think of aggregating aggregators with one or two prices like this example ?:
image
Of course, instead of displaying an icon like this avatar we would display the price.

**Comment by nathanqueija** [comment]
Now if you click on the aggregator the map will frame the aggregators' markers

**Comment by gusaiani** [comment]
@nathanqueija I think this is a good improvement.

Can we:
1. drop the `+` from each aggregator?
On hover, use `blue.dark` only on the background? (the UX idea being that the cursor turns to a `pointer` anyway on hover, and a more subtle shift like this makes the app less tiresome for longer sessions.

**Pull request merged**
